#! /usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'ds4drv==0.5.0','console_scripts','ds4drv'
__requires__ = 'ds4drv==0.5.0'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('ds4drv==0.5.0', 'console_scripts', 'ds4drv')()
    )
