#!/bin/sh -e

PKG="ds4drv"

if [ -e /etc/init.d/ds4drv ]; then
  update-rc.d ds4drv disable
  update-rc.d -f ds4drv remove
fi

if [ -e /etc/bluetooth/main.conf ]; then
  sed -i -e 's/AutoEnable=true #ds4drv#//g' /etc/bluetooth/main.conf
fi

#DEBHELPER
