#!/bin/sh -e

PKG="ds4drv"

if [ -e /etc/init.d/ds4drv ]; then
  update-rc.d -f ds4drv defaults
  update-rc.d ds4drv enable
fi

if [ -e /etc/bluetooth/main.conf ]; then
  echo "AutoEnable=true #ds4drv#" >> /etc/bluetooth/main.conf
fi

#DEBHELPER
