#!/bin/sh -e

PKG="ds4drv"

if [ -e /etc/init.d/ds4drv ]; then
  update-rc.d -f ds4drv defaults
  update-rc.d ds4drv enable
fi

if [ -e /etc/bluetooth/main.conf ]; then
  # remove the addition from previous versions of this package!
  sed -i -e 's/AutoEnable=true#ds4drv#//g' /etc/bluetooth/main.conf

  # ensure AutoEnable is true
  if ! grep -q "AutoEnable=true" /etc/bluetooth/main.conf;
  then
    echo "AutoEnable=true #ds4drv#" >> /etc/bluetooth/main.conf
  fi
fi

# symlink the service into the multi-user.wants folder
if [ ! -e /lib/systemd/system/multi-user.target.wants/ds4drv.service ];
then
  ln -s /lib/systemd/system/ds4drv.service /lib/systemd/system/multi-user.target.wants/ds4drv.service
fi
#DEBHELPER
