#!/usr/bin/expect

puts "** This script must be run as sudo **"
puts "Searching for PS4 Controller..."

log_user 0
set prompt "#"

spawn bluetoothctl -a
expect "Agent registered"
expect $prompt

send -- "default-agent\r"
expect "agent request successful"

send -- "scan on\r"
expect "Discovery started"

set timeout 15

expect {
  -re {([A-Z0-9:]{17}) Wireless Controller} {
      set PS4_MAC $expect_out(1,string)
      log_user 1
      send -- "trust $PS4_MAC\r"
      expect "trust succeeded"

      send -- "pair $PS4_MAC\r"
      expect "Pairing successful"
      log_user 0
      expect $prompt
  }
  timeout {
      puts "No Controller Found"
  }
}

send -- "scan off\r"
expect "Discovery stopped"
expect $prompt

send "quit\r"
expect "eof"
